export const GET_ADMIN_INVOICE_REQUEST = "GET_ADMIN_INVOICE_REQUEST";
export const GET_ADMIN_INVOICE_SUCCESS = "GET_ADMIN_INVOICE_SUCCESS";
export const GET_ADMIN_INVOICE_FAIL = "GET_ADMIN_INVOICE_FAIL";

export const CREATE_ADMIN_INVOICE_REQUEST = "CREATE_ADMIN_INVOICE_REQUEST";
export const CREATE_ADMIN_INVOICE_SUCCESS = "CREATE_ADMIN_INVOICE_SUCCESS";
export const CREATE_ADMIN_INVOICE_FAIL = "CREATE_ADMIN_INVOICE_FAIL";

export const CREATE_MANAGE_PORTAL_INVOICE_REQUEST = "CREATE_MANAGE_PORTAL_INVOICE_REQUEST";
export const CREATE_MANAGE_PORTAL_INVOICE_SUCCESS = "CREATE_MANAGE_PORTAL_INVOICE_SUCCESS";
export const CREATE_MANAGE_PORTAL_INVOICE_FAIL = "CREATE_MANAGE_PORTAL_INVOICE_FAIL";

export const UPDATE_ADMIN_INVOICE_REQUEST = "UPDATE_ADMIN_INVOICE_REQUEST";
export const UPDATE_ADMIN_INVOICE_SUCCESS = "UPDATE_ADMIN_INVOICE_SUCCESS";
export const UPDATE_ADMIN_INVOICE_FAIL = "UPDATE_ADMIN_INVOICE_FAIL";

export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";
export const SEND_MAIL_FAIL = "SEND_MAIL_FAIL";